name: qonto
description: Qonto REST API implementation on Dart, based on Qonto REST API v2.
version: 0.1.0
homepage: https://github.com/Clique-Paris/qonto

environment:
  sdk: '>=2.7.0 <3.0.0'

dev_dependencies:
  pedantic: ^1.8.0
  test: ^1.6.0
